export default {
  OPEN_MENU:  'APP.OPEN_MENU',
  CLOSE_MENU: 'APP.CLOSE_MENU',
  OPEN_CREATE_TASK_DIALOG: 'APP.OPEN_CREATE_TASK_DIALOG',
  CLOSE_CREATE_TASK_DIALOG: 'APP.CLOSE_CREATE_TASK_DIALOG',
  OPEN_EDIT_TASK_DIALOG: 'APP.OPEN_EDIT_TASK_DIALOG',
  CLOSE_EDIT_TASK_DIALOG: 'APP.CLOSE_EDIT_TASK_DIALOG'
}
