export default {
  CREATE_TASK: 'TASK.CREATE_TASK',
  UPDATE_TASK: 'TASK.UPDATE_TASK',
  DELETE_TASK: 'TASK.DELETE_TASK',
  TITLE_CHANGED: 'TASK.TITLE_CHANGED',
  RECIPIENT_CHANGED: 'TASK.RECIPIENT_CHANGED',
  DATE_CHANGED: 'TASK.DATE_CHANGED',
  TIME_CHANGED: 'TASK.TIME_CHANGED',
  REPEAT_EVERY_DAY: 'TASK.REPEAT_EVERY_DAY',
  REPEAT_EVERY_WEEK: 'TASK.REPEAT_EVERY_WEEK'
}
